version: '3.1'

services:
  db:
    image: mysql
    container_name: docker-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: snorlax
      MYSQL_DATABASE: pokemon
      MYSQL_USER: bitless
      MYSQL_PASSWORD: snorlax
    volumes:
      - ./schemas:/var/lib/mysql
    
